# Makefile for support utilities

all:
	gcc bin2mem.c -o bin2mem

	gcc bin2mem4.c -o bin2mem4

	gcc bin2rom.c -o bin2rom

	gcc mem2bin.c -o mem2bin

clean:
	@rm -f bin2mem bin2mem.exe bin2mem4 bin2mem4.exe bin2rom bin2rom.exe mem2bin mem2bin.exe
